=== endlesslydivided/CMP_LABS/XML и SVG/Лабораторная работа 13/UNIVERSITIES.dtd
<!ELEMENT UNIVERSITIES (UNIVERSITY+)>
<!ELEMENT UNIVERSITY (UNIVERSITY_NAME,PASS_POINT,PLAN,CITY)>
<!ELEMENT UNIVERSITY_NAME (#PCDATA)>
<!ELEMENT PASS_POINT (#PCDATA)>
<!ELEMENT PLAN (#PCDATA)>
<!ELEMENT CITY (#PCDATA)>

=== endlesslydivided/CMP_LABS/XML и SVG/Лабораторная работа 13/Задание 1/task01.xml
<?xmlversion = "1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="1.css"?>
<!DOCTYPE UNIVERSITIES SYSTEM "UNIVERSITIES.dtd">
<UNIVERSITIES>
<UNIVERSITY>
<UNIVERSITY_NAME> БГУИР </UNIVERSITY_NAME>
<PASS_POINT> 323</PASS_POINT>
<PLAN> 150 </PLAN>
<CITY> Минск </CITY>
</UNIVERSITY>
<UNIVERSITY>
<UNIVERSITY_NAME> БНТУ </UNIVERSITY_NAME>
<PASS_POINT> 330</PASS_POINT>
<PLAN> 200 </PLAN>
<CITY> Минск </CITY>
</UNIVERSITY>
<UNIVERSITY>
<UNIVERSITY_NAME> БРУ </UNIVERSITY_NAME>
<PASS_POINT> 250</PASS_POINT>
<PLAN> 200 </PLAN>
<CITY> Могилёв </CITY>
</UNIVERSITY>
</UNIVERSITIES>
